[package]
name = "shelly-reset"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.3", features = ["derive"] }
btleplug = "0.11"
tokio = { version = "1.41", features = ["full"] }
uuid = "1.2"
futures = "0.3.31"
